CREATE TABLE IF NOT EXISTS tournament_badges (
	id SERIAL PRIMARY KEY UNIQUE,
	tournament_id BIGINT REFERENCES tournaments(id) ON DELETE CASCADE ON UPDATE CASCADE,
	badge_id BIGINT REFERENCES badges(id) ON DELETE CASCADE ON UPDATE CASCADE
);