name: Build Docker Container Development

on:
  # push:
  #   branches:
  #     - development
  workflow_dispatch:

concurrency: development

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME_DEV }}
          password: ${{ secrets.DOCKER_TOKEN_DEV }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dotsboardgamecafe/dots-app:api-build-${{ github.run_number }}
      - 
        name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          port: ${{ secrets.SSH_PORT_DEV }}
          script: |
            cd dots-api
            docker login
            sed -i~ "/^API_IMAGE=/s/=.*/=dotsboardgamecafe\/dots-app:api-build-${{github.run_number}}/g" .env
            cat .env
            docker compose up -d
